(() => {
  const icon = (path) => `<span class="runtime-icon" aria-hidden="true"><svg viewBox="0 0 24 24">${path}</svg></span>`;
  const arrow = '<span class="esteem-cta-arrow" aria-hidden="true">→</span>';

  const pages = {
    "10-5": {
      slug: "10-5-kw-solar-system", title: "10.5kW Solar System", eyebrow: "HIGHER-CAPACITY HOME SOLAR",
      hero: "A practical solar solution for homes with higher daytime electricity use.",
      intro: "A 10.5kW system can suit larger households, homes with significant daytime demand, or properties planning for future energy needs. The right configuration depends on the home, roof and local network requirements.",
      image: "../assests/about/modern-home-solar-panels.webp", alt: "Large modern Australian home with rooftop solar panels",
      stats: [["10.5kW", "System size"], ["24–27", "Approximate panels at 390–440W"], ["35–45kWh", "Indicative daily output"], ["Higher use", "Household suitability"]],
      overviewTitle: "What Is a 10.5kW Solar System?", overview: "A 10.5kW solar system combines a larger rooftop panel array with an inverter configuration selected for the property. It can generate more daytime energy than smaller residential systems, which may be useful for larger homes, electric appliances or households with people home during the day.",
      overviewMore: "Whether a 10.5kW design is suitable depends on available roof area, household consumption, phase supply, export settings and the local network. A property assessment is needed before equipment is selected.",
      features: [["More daytime capacity", "Designed for households with a higher daytime energy profile."], ["Panel flexibility", "The final panel count can be matched to the selected panel wattage and roof layout."], ["Battery ready", "A compatible battery can be considered where storage suits the energy pattern."], ["Monitoring", "Many modern inverters provide generation and consumption monitoring."], ["Tailored design", "System sizing can account for shading, orientation and future energy needs."], ["Professional installation", "Roof and electrical requirements are assessed before installation."]],
      practicalTitle: "10.5kW System Planning Considerations", practical: "A 10.5kW system generally needs more usable roof area than a standard residential array. Panel layout, roof structure, cable paths, switchboard condition and the property’s single-phase or three-phase supply can all affect the final design.", practicalList: ["Panel wattage and final panel count", "Roof area, pitch, orientation and shading", "Single-phase or three-phase electrical supply", "Network export settings and any required approvals", "Battery compatibility and monitoring requirements"],
      suitabilityTitle: "Who Could Consider a 10.5kW System?", suitability: ["Larger homes with higher electricity consumption", "Households using air conditioning, pools or other daytime loads", "Homes with strong daytime solar usage", "Properties considering a compatible battery or electric vehicle"],
      process: ["Review electricity usage and future energy plans.", "Assess roof area, orientation, shading and electrical supply.", "Design the array, inverter and optional storage around the property.", "Complete installation, testing, monitoring setup and handover."],
      benefits: ["More solar energy available during daylight", "Potentially lower reliance on grid electricity", "A scalable base for compatible storage", "Better alignment with higher daytime demand", "Clearer visibility through system monitoring"],
      faqs: [["Is 10.5kW suitable for every home?", "No. Roof space, usage, electrical supply and network requirements all need to be assessed."], ["How many panels are needed?", "The count depends on panel wattage. A 10.5kW array could use approximately 24–27 panels in the 390–440W range."], ["How much power might it produce?", "A suitably designed system may generate around 35–45kWh per day in suitable conditions. Actual output varies by location and weather."], ["Can it be installed on single-phase power?", "It may be possible, but the design and export settings depend on the property and local network."], ["Can a battery be added later?", "A compatible battery may be added depending on the inverter, wiring and future system design."], ["What affects price?", "Equipment selection, roof access, electrical upgrades, location, incentives and installation complexity can all affect the quote."]]
    },
    "13-2": {
      slug: "13-2-kw-solar-system", title: "13.2kW Solar System", eyebrow: "HIGH-CAPACITY SOLAR",
      hero: "Solar capacity for large homes and selected small-business energy profiles.",
      intro: "A 13.2kW system can be considered where electricity use is high and there is enough suitable roof area for a larger array. Design, export and approval requirements are property and network specific.",
      image: "../assests/about/modern-home-solar-panels.webp", alt: "Contemporary Australian home with a large rooftop solar array",
      stats: [["13.2kW", "System size"], ["30–33", "Approximate panels at 400–440W"], ["45–56kWh", "Indicative daily output"], ["Large loads", "Home or selected small business"]],
      overviewTitle: "What Is a 13.2kW Solar System?", overview: "A 13.2kW solar system is a high-capacity panel array designed for properties that use more electricity than a typical smaller home system can cover during daylight. It may suit large households and some small businesses, subject to a detailed assessment.",
      overviewMore: "Larger systems require careful consideration of roof layout, inverter capacity, phase supply, export limitations and local network approval. These requirements cannot be confirmed without a property and connection review.",
      features: [["High-capacity generation", "A larger array can provide more daytime solar for higher energy use."], ["Large-home suitability", "Useful to consider when household consumption is consistently high."], ["Selected business use", "May suit some small-business premises after a commercial assessment."], ["Storage compatibility", "Battery storage can be considered where it fits the load profile."], ["Export-aware design", "System settings can be planned around local network requirements."], ["Performance monitoring", "Compatible inverter platforms can provide system visibility."]],
      practicalTitle: "13.2kW Design and Approval Considerations", practical: "A high-capacity system needs enough roof area and an electrical design that suits the property. Phase configuration, export limits, protection equipment and network approval may affect the equipment selection and final system size.", practicalList: ["Three-phase suitability may be relevant for larger systems", "The local network may set export or approval requirements", "Roof structure and cable routes need to be assessed", "Battery charging can change the way surplus energy is used", "Final production depends on location, orientation and shading"],
      suitabilityTitle: "Where Could a 13.2kW System Fit?", suitability: ["Large homes with substantial annual electricity use", "Homes with strong daytime loads", "Selected small businesses with suitable roof area", "Properties planning for storage or future electrification"],
      process: ["Review consumption, phase supply and the property’s energy goals.", "Complete a roof, shading, structural and electrical assessment.", "Confirm equipment, export settings and any network approval pathway.", "Install, test, connect monitoring and provide a system handover."],
      benefits: ["More available solar power for high daytime loads", "Potentially less grid energy purchased during production hours", "A larger platform for compatible battery storage", "Useful visibility into generation and consumption", "A design that can account for future energy needs"],
      faqs: [["Is 13.2kW only for businesses?", "No. It can suit some large homes as well as selected small-business properties, subject to assessment."], ["How many panels are needed?", "Approximately 30–33 panels may be required when using panels around 400–440W."], ["Will network approval be needed?", "It may be, depending on system size, phase supply, export settings and local network requirements."], ["Is three-phase power required?", "Not always, but phase configuration is an important part of designing a larger system."], ["Can batteries be added?", "A compatible storage solution may be considered after checking inverter and electrical compatibility."], ["Can output be guaranteed?", "No. Generation is an estimate and varies with location, weather, roof orientation, shading and system design."]]
    },
    "19-5": {
      slug: "19-5-kw-solar-system", title: "19.5kW Solar System", eyebrow: "LARGE-SCALE SOLAR",
      hero: "A high-capacity solar option for large properties and selected commercial applications.",
      intro: "A 19.5kW system is designed for properties with high daytime energy demand and substantial suitable roof area. It is not a universal fit; a detailed site, structural, electrical and network assessment is essential.",
      image: "../assests/about/solar-installers-at-work.webp", alt: "Solar installer working safely on a large residential rooftop",
      stats: [["19.5kW", "System size"], ["45–53", "Approximate panels at 370–440W"], ["65–82kWh", "Indicative daily output"], ["Detailed design", "Site assessment required"]],
      overviewTitle: "What Is a 19.5kW Solar System?", overview: "A 19.5kW solar system uses a large panel array to support significant daytime energy demand. It may be considered for large homes, acreage properties, workshops or selected commercial applications where the roof, electrical supply and network connection can support the design.",
      overviewMore: "At this scale, the design must account for roof structure, access, inverter arrangement, three-phase supply, export limitations and any approval pathway. The final design should be based on a detailed site assessment rather than a standard package.",
      features: [["High daytime capacity", "Suitable to investigate where daytime energy demand is substantial."], ["Large-array planning", "Panel count and layout are designed around available roof area."], ["Three-phase considerations", "Larger systems often require careful phase and connection planning."], ["Storage integration", "Battery charging and load shifting can be considered in the design."], ["Network-aware setup", "Export limitations and approval requirements are reviewed early."], ["Monitoring and commissioning", "Testing and monitoring help verify the installed system."]],
      practicalTitle: "19.5kW Site Assessment Requirements", practical: "A system of this size should not be specified from roof area alone. Structural condition, access, switchboard capacity, three-phase configuration, cable runs, inverter location and network requirements all influence feasibility and cost.", practicalList: ["Confirm usable roof area and structural suitability", "Review three-phase supply and switchboard capacity", "Check network export limitations and approval requirements", "Plan inverter locations, cable routes and safety access", "Consider battery storage and the property’s daytime load"],
      suitabilityTitle: "Who Might Consider a 19.5kW System?", suitability: ["Large residential properties with high energy consumption", "Acreage homes or properties with substantial daytime loads", "Selected workshops or small commercial applications", "Sites with enough roof area and appropriate electrical infrastructure"],
      process: ["Complete a detailed energy, roof, structural and electrical review.", "Develop a large-array layout and confirm inverter and phase requirements.", "Work through connection, export and approval requirements.", "Install, test, commission monitoring and hand over the system."],
      benefits: ["More solar capacity for high daytime demand", "Potential to offset more purchased grid energy", "A planned base for battery and load management", "Better insight through monitoring and commissioning", "A system designed around the property rather than a generic package"],
      faqs: [["Is 19.5kW suitable for every large home?", "No. Roof, structure, electrical supply, network conditions and energy use must all support the design."], ["How many panels are needed?", "Approximately 45–53 panels may be required with panels in the 370–440W range."], ["Will three-phase power be relevant?", "Often. The property’s phase configuration and connection requirements must be checked."], ["Are exports to the grid unlimited?", "No. Export settings and limits can depend on the local network and approved connection."], ["Can a battery be added?", "A compatible battery and inverter configuration may be designed where storage is appropriate."], ["What is the first step?", "Request a site-specific assessment covering energy use, roof structure, electrical infrastructure and network requirements."]]
    },
    "battery": {
      slug: "battery-storage", title: "Solar Battery Storage", eyebrow: "STORE MORE OF YOUR SOLAR",
      hero: "Use more of the solar energy your home generates, day and night.",
      intro: "Solar battery storage can store surplus daytime solar for later use. Whether storage is suitable depends on your energy pattern, battery capacity, inverter compatibility, backup goals and installation requirements.",
      image: "/assets/site-images/product/Solar-Batteries.png", alt: "Solar battery storage equipment from the original Esteem Energy media library",
      stats: [["Store", "Surplus daytime solar"], ["Use later", "Evening and overnight energy"], ["Design specific", "Usable capacity varies"], ["Optional backup", "Requires compatible configuration"]],
      overviewTitle: "What Is Solar Battery Storage?", overview: "A solar battery stores electrical energy generated by solar panels so it can be used later, often when the sun is no longer producing. This can increase self-consumption and reduce the amount of solar energy exported unused.",
      overviewMore: "Battery systems include a rated capacity and a usable capacity. The inverter, battery chemistry, installation location and control settings all matter. A battery does not automatically provide backup power during a blackout; backup requires compatible equipment and the correct installation configuration.",
      features: [["Solar charging", "Surplus solar can be directed into storage during the day."], ["Evening use", "Stored energy can support household loads after solar production falls."], ["Usable capacity", "The available energy depends on the battery’s design and operating limits."], ["AC or DC coupled", "The right configuration depends on the existing or planned inverter."], ["Monitoring apps", "Many systems provide visibility into charge, discharge and usage."], ["Safety-led installation", "Location, ventilation, clearances and electrical requirements are assessed."]],
      practicalTitle: "Battery Storage Configuration", practical: "Battery design should match how a home uses energy rather than simply maximising capacity. The installer can review solar production, evening loads, desired backup circuits, inverter compatibility and the space available for safe installation.", practicalList: ["Choose capacity around actual usage and solar surplus", "Confirm rated capacity versus usable capacity", "Check AC-coupled or DC-coupled compatibility", "Decide whether backup power is required", "Plan monitoring, isolation, clearances and safe access"],
      suitabilityTitle: "When Could a Battery Be Useful?", suitability: ["Homes exporting a meaningful amount of surplus solar", "Households with regular evening electricity use", "Properties seeking greater self-consumption", "Homes considering backup for selected circuits with compatible equipment"],
      process: ["Review bills, solar production and household usage patterns.", "Assess the existing inverter, switchboard and installation location.", "Select a compatible battery and decide whether backup is required.", "Install, configure controls, test operation and explain monitoring."],
      benefits: ["Use more self-generated solar energy", "Shift stored energy into evening usage", "Reduce reliance on grid electricity at selected times", "Add visibility through monitoring", "Consider backup power where the configuration supports it"],
      faqs: [["Does every battery provide blackout backup?", "No. Backup requires compatible equipment, backup circuits and the correct installation configuration."], ["What is usable capacity?", "Usable capacity is the portion of a battery’s rated capacity available for normal operation; it varies by model and settings."], ["Can a battery be added to existing solar?", "Often it can, but the existing inverter, switchboard and wiring must be checked."], ["What are AC-coupled and DC-coupled systems?", "AC-coupled systems connect on the AC side, while DC-coupled systems share a DC-side arrangement. Suitability depends on the system design."], ["How long does a battery last?", "Service life depends on model, cycling, temperature, settings and maintenance. The selected product documentation should be reviewed."], ["Can I monitor the battery from an app?", "Many systems offer app monitoring, subject to the chosen inverter and battery platform."]]
    },
    "residential": {
      slug: "residential-solar", title: "Residential Solar Systems", eyebrow: "SOLAR FOR AUSTRALIAN HOMES",
      hero: "A clearer way to generate, use and manage energy at home.",
      intro: "Residential solar can help households generate electricity from sunlight, use more of their own energy and make informed decisions about batteries, system size and future energy needs.",
      image: "../assests/about/modern-home-solar-panels.webp", alt: "Australian residential home with solar panels on the roof",
      stats: [["Panels", "Capture sunlight"], ["Inverter", "Converts DC to AC"], ["Optional battery", "Store surplus energy"], ["Designed for home", "Usage-led system sizing"]],
      overviewTitle: "How Does Residential Solar Work?", overview: "Solar panels capture sunlight and produce DC electricity. An inverter converts that energy into AC electricity for household appliances. The home uses available solar first, while surplus may be exported or stored in a compatible battery.",
      overviewMore: "A good residential system considers electricity use, roof suitability, system size, phase supply, monitoring, battery plans and the way the household uses energy throughout the day.",
      features: [["Usage-led sizing", "System capacity is considered around the home’s electricity profile."], ["Roof assessment", "Orientation, pitch, shading and available area shape the design."], ["Single or three-phase", "The property’s supply is considered when choosing equipment."], ["Battery option", "Storage can be assessed when evening use or backup is a priority."], ["Energy monitoring", "Compatible systems can show generation and household usage."], ["Ongoing support", "Clear handover and support help households understand their system."]],
      practicalTitle: "Choosing a Residential System", practical: "The right size is not determined by roof area alone. Household bills, daytime usage, future appliances, shade, roof structure, electrical supply and battery plans all contribute to a practical recommendation.", practicalList: ["Review household usage and electricity bills", "Assess roof area, orientation, pitch and shading", "Consider single-phase or three-phase supply", "Compare solar-only and battery-ready options", "Plan monitoring and ongoing system support"],
      suitabilityTitle: "Residential Solar System Sizes", suitability: ["Smaller homes and moderate usage can consider compact systems", "Medium homes can explore the 6.6kW range", "Larger homes may consider 10.5kW or 13.2kW options", "High-demand properties may require a detailed 19.5kW assessment"],
      process: ["Discuss the home, electricity use and future energy needs.", "Inspect roof suitability, shading, access and electrical supply.", "Design the panels, inverter, monitoring and optional battery plan.", "Install, test, explain the system and provide ongoing support."],
      benefits: ["Generate renewable energy at home", "Potentially reduce purchased grid electricity", "Make better use of daytime solar production", "Consider battery storage for later use", "Improve visibility of household energy use"],
      faqs: [["What size solar system does my home need?", "It depends on usage, roof area, location, shading, phase supply and future energy plans."], ["Can solar work on any roof?", "Many roof types can support solar, but structure, access, orientation and shading need to be assessed."], ["Can I add a battery later?", "A battery may be added when the inverter and electrical design are compatible."], ["Does residential solar work in a blackout?", "Standard grid-connected systems usually shut down during outages unless compatible backup equipment is installed."], ["How much maintenance is needed?", "Monitoring and periodic visual checks are useful; specific maintenance depends on the equipment and site."], ["Which system sizes can I compare?", "Compare the 6.6kW, 10.5kW, 13.2kW and 19.5kW options below, then request a site-specific recommendation."]],
      sizeLinks: [["6.6kW Solar System", "/6-6-kw-solar-system/"], ["10.5kW Solar System", "/10-5-kw-solar-system/"], ["13.2kW Solar System", "/13-2-kw-solar-system/"], ["19.5kW Solar System", "/19-5-kw-solar-system/"]]
    },
    "installation": {
      slug: "installation", title: "Professional Solar Installation", eyebrow: "FROM ASSESSMENT TO HANDOVER",
      hero: "A considered installation process built around your property and energy needs.",
      intro: "Professional solar installation brings together energy review, roof assessment, system design, electrical work, testing, monitoring and handover. Timing depends on system size, roof condition, approvals and property requirements.",
      image: "/assets/site-images/installation/The-Solar-Installation-Process_-What-to-Expect-from-Start-to-Finish-1.png", alt: "Solar installation process from the original Esteem Energy media library",
      stats: [["Review", "Usage and property"], ["Design", "System and equipment"], ["Install", "Panels and inverter"], ["Handover", "Testing and monitoring"]],
      overviewTitle: "What Does Solar Installation Involve?", overview: "A solar installation is more than placing panels on a roof. It includes understanding how the property uses electricity, checking the roof and electrical infrastructure, designing the system, installing equipment safely and setting up monitoring.",
      overviewMore: "Every property is different. Approval pathways, roof access, electrical work, equipment availability and site conditions can influence timing and the final installation plan.",
      features: [["Initial consultation", "Clarify energy goals, current usage and future plans."], ["Property assessment", "Review roof condition, layout, shading, access and electrical supply."], ["System design", "Select panel layout, inverter, monitoring and optional storage."], ["Safe installation", "Install panels, inverter and electrical equipment for the property."], ["Testing", "Check connections, operation, monitoring and system performance."], ["Handover", "Explain the system, controls and ongoing support requirements."]],
      practicalTitle: "The Solar Installation Process", practical: "A clear process helps identify site requirements early and keeps the final system aligned with the home’s energy needs. The exact sequence can vary with system size, roof type, approvals and electrical work.", practicalList: ["Initial consultation and electricity-usage review", "Roof inspection and property assessment", "System design and product selection", "Approval process and installation preparation", "Panel, inverter and electrical installation", "Testing, monitoring setup, handover and support"],
      suitabilityTitle: "What Can Affect Installation Planning?", suitability: ["System size and number of panels", "Roof material, pitch, access and structural condition", "Switchboard condition and electrical requirements", "Approvals, inspections and network requirements", "Battery, monitoring or other optional equipment"],
      process: ["Consultation: review usage, goals and the property.", "Assessment: inspect roof, shade, access and electrical infrastructure.", "Design: select system size, equipment, layout and optional storage.", "Installation: fit panels and inverter, complete connections and testing.", "Handover: set up monitoring and explain operation and support."],
      benefits: ["A system planned around the actual property", "Clearer expectations about equipment and site work", "Professional connection and testing process", "Monitoring setup for better system visibility", "Support after installation and handover"],
      faqs: [["How long does installation take?", "Timing varies with system size, roof condition, approvals, electrical work and property requirements; no single timeframe applies to every job."], ["What happens during the first consultation?", "The team discusses electricity use, property goals, roof suitability and possible system options."], ["Is a roof inspection required?", "A roof and access assessment helps determine layout, mounting, safety and installation requirements."], ["Does the installer arrange approvals?", "The required approval pathway depends on the property and local network; this is confirmed as part of project planning."], ["Will monitoring be set up?", "Where supported by the selected equipment, monitoring can be configured and explained during handover."], ["What happens after installation?", "The system is tested, the controls are explained and ongoing support information is provided."]]
    }
  };

  const featureIcon = (index) => [
    '<path d="M13 2 3 14h9l-1 8 10-12h-9l1-8z"/>',
    '<path d="M12 2 2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>',
    '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    '<path d="M4 19V5m0 14h16M8 16v-3m4 3V8m4 8v-6"/>',
    '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6-8 10-8 10z"/>',
    '<path d="M12 3v18M3 12h18M5.6 5.6l12.8 12.8M18.4 5.6 5.6 18.4"/>'
  ][index % 6];

  const renderFaqs = (items) => items.map(([question, answer], index) => `
    <div class="product-faq-item${index === 0 ? " is-open" : ""}">
      <button class="product-faq-trigger" aria-expanded="${index === 0}" aria-controls="runtime-faq-${index}"><span>${question}</span><span class="product-faq-icon" aria-hidden="true">+</span></button>
      <div class="product-faq-content" id="runtime-faq-${index}" role="region"><div class="product-faq-answer">${answer}</div></div>
    </div>`).join("");

  const renderPage = (data) => {
    const main = document.querySelector("main#main");
    if (!main || main.dataset.productPageRendered) return;
    main.dataset.productPageRendered = "true";
    const stats = data.stats.map(([value, label]) => `<div class="prod-highlight-card"><strong>${value}</strong><span>${label}</span></div>`).join("");
    const features = data.features.map(([title, text], index) => `<article class="prod-feature-card" data-reveal data-reveal-delay="${index % 3}"><span class="prod-feature-icon">${icon(featureIcon(index))}</span><h3>${title}</h3><p>${text}</p></article>`).join("");
    const suitability = data.suitability.map((item) => `<li>${item}</li>`).join("");
    const process = data.process.map((item, index) => `<li class="prod-step-card" data-reveal><span class="prod-step-num">${String(index + 1).padStart(2, "0")}</span><div>${item}</div></li>`).join("");
    const benefits = data.benefits.map((item) => `<li>${item}</li>`).join("");
    const sizeLinks = data.sizeLinks ? `<div class="runtime-size-links"><h3>Compare system sizes</h3><div>${data.sizeLinks.map(([label, href]) => `<a href="${href}">${label} ${arrow}</a>`).join("")}</div></div>` : "";
    main.innerHTML = `
      <nav class="prod-container runtime-breadcrumb" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><span>Products</span></li><li aria-hidden="true">/</li><li aria-current="page">${data.title}</li></ol></nav>
      <section class="prod-hero" aria-labelledby="runtime-hero-title"><div class="prod-container prod-hero-grid"><div class="prod-hero-copy" data-reveal><p class="prod-eyebrow">${data.eyebrow}</p><h1 id="runtime-hero-title">${data.title}</h1><p class="prod-lead">${data.hero} ${data.intro}</p><div class="prod-actions"><button class="esteem-primary-cta" type="button" data-open-quote-modal aria-haspopup="dialog" aria-controls="solar-lead-dialog"><span class="esteem-cta-label">Get a Free Quote</span>${arrow}</button><a class="esteem-secondary-cta" href="tel:1300220354"><span>Call 1300 220 354</span>${arrow}</a></div></div><div class="prod-hero-visual prod-parallax" data-reveal data-reveal-delay="1"><img src="${data.image}" width="1600" height="1068" alt="${data.alt}" fetchpriority="high"><div class="prod-spec-card"><div class="prod-spec-title">At a glance</div>${data.stats.slice(0, 3).map(([label, value]) => `<div class="prod-spec-item"><span>${value}</span><span>${label}</span></div>`).join("")}</div></div></div></section>
      <section class="prod-overview"><div class="prod-container"><div class="prod-highlight-grid" data-reveal>${stats}</div><p class="prod-note">Performance, suitability and installation requirements vary by property, location, equipment selection and weather conditions.</p></div></section>
      <section class="prod-section" aria-labelledby="runtime-overview-title"><div class="prod-container prod-split"><div class="prod-copy" data-reveal><div class="prod-title-group"><p class="prod-eyebrow">PRODUCT OVERVIEW</p><h2 id="runtime-overview-title">${data.overviewTitle}</h2><p>${data.overview}</p><p>${data.overviewMore}</p></div></div><div class="prod-visual runtime-illustration" data-reveal data-reveal-delay="1"><div class="runtime-flow"><div>${icon('<path d="M3 10 12 3l9 7v9H3z"/><path d="M7 19v-6h10v6M9 10h6"/>')}<span>Solar</span></div><b>→</b><div>${icon('<rect x="6" y="3" width="12" height="18" rx="2"/><path d="M9 7h6M9 17h6"/>')}<span>Inverter</span></div><b>→</b><div>${icon('<path d="M3 11 12 4l9 7v8H3z"/><path d="M10 19v-5h4v5"/>')}<span>Home</span></div></div><p>Surplus energy can be exported or stored where the system supports it.</p></div></div></section>
      <section class="prod-section prod-features" aria-labelledby="runtime-features-title"><div class="prod-container"><div class="prod-title-group" data-reveal><p class="prod-eyebrow">KEY FEATURES</p><h2 id="runtime-features-title">Designed around how your property uses energy</h2></div><div class="prod-features-grid">${features}</div></div></section>
      <section class="prod-section prod-checklist-section" aria-labelledby="runtime-practical-title"><div class="prod-container"><div class="prod-title-group" data-reveal><p class="prod-eyebrow">PRACTICAL INFORMATION</p><h2 id="runtime-practical-title">${data.practicalTitle}</h2><p>${data.practical}</p></div><div class="runtime-list-grid"><ul class="prod-icon-list" data-reveal>${data.practicalList.map((item) => `<li>${item}</li>`).join("")}</ul><div class="runtime-callout" data-reveal data-reveal-delay="1"><span>Assessment first</span><p>Final equipment, capacity, output and cost should be confirmed through a property-specific assessment.</p></div></div></div></section>
      <section class="prod-section" aria-labelledby="runtime-suitable-title"><div class="prod-container prod-split prod-split--reverse"><div class="prod-copy" data-reveal><div class="prod-title-group"><p class="prod-eyebrow">SUITABILITY</p><h2 id="runtime-suitable-title">${data.suitabilityTitle}</h2><ul class="prod-icon-list">${suitability}</ul>${sizeLinks}</div></div><div class="prod-visual prod-parallax" data-reveal data-reveal-delay="1"><img src="${data.image}" width="1400" height="788" alt="${data.alt}" loading="lazy"></div></div></section>
      <section class="prod-section prod-works" aria-labelledby="runtime-process-title"><div class="prod-container"><div class="prod-title-group" data-reveal><p class="prod-eyebrow">HOW IT WORKS</p><h2 id="runtime-process-title">A clear path from consultation to support</h2></div><ol class="prod-steps-grid runtime-process-grid">${process}</ol></div></section>
      <section class="prod-section prod-features" aria-labelledby="runtime-benefits-title"><div class="prod-container prod-split"><div class="prod-copy" data-reveal><div class="prod-title-group"><p class="prod-eyebrow">BENEFITS</p><h2 id="runtime-benefits-title">What this approach can help with</h2><ul class="prod-icon-list">${benefits}</ul></div></div><div class="prod-visual runtime-benefit-visual" data-reveal data-reveal-delay="1"><div><strong>Energy, planned clearly</strong><p>Good solar decisions balance equipment, usage, property conditions and future needs.</p></div></div></div></section>
      <section class="prod-section" aria-labelledby="runtime-why-title"><div class="prod-container"><div class="prod-title-group runtime-centered" data-reveal><p class="prod-eyebrow">OUR SERVICE COMMITMENT</p><h2 id="runtime-why-title">Why Choose Esteem Energy?</h2><p>We make the solar journey clear, from consultation and system design to professional installation and ongoing support.</p></div><div class="prod-checklist-grid runtime-why-grid"><div class="prod-checklist-card" data-reveal><h3>Tailored recommendations</h3><p>Options are considered around your property, energy use and goals.</p></div><div class="prod-checklist-card" data-reveal data-reveal-delay="1"><h3>Quality-focused installation</h3><p>Planning considers safety, performance, reliability and long-term value.</p></div><div class="prod-checklist-card" data-reveal data-reveal-delay="2"><h3>Clear customer support</h3><p>Support remains available before, during and after the solar journey.</p></div></div></div></section>
      <section class="prod-final-wrap"><div class="prod-container"><div class="prod-final" data-reveal><div><p class="prod-eyebrow">READY TO EXPLORE SOLAR?</p><h2>Talk through the right ${data.title.toLowerCase()} option</h2><p>Speak with the Esteem Energy team for a personalised assessment and quotation based on your property and energy needs.</p></div><div class="prod-actions prod-final-actions"><button class="esteem-primary-cta esteem-primary-cta--dark" type="button" data-open-quote-modal aria-haspopup="dialog" aria-controls="solar-lead-dialog"><span class="esteem-cta-label">Get a Free Quote</span>${arrow}</button><a class="esteem-secondary-cta esteem-secondary-cta--dark" href="tel:1300220354"><span>Call 1300 220 354</span>${arrow}</a></div></div></div></section>
      <section class="prod-section prod-faq-section" id="faqs" aria-labelledby="runtime-faq-title"><div class="prod-container"><div class="prod-title-group runtime-centered" data-reveal><p class="prod-eyebrow">YOUR QUESTIONS ANSWERED</p><h2 id="runtime-faq-title">Frequently Asked Questions</h2><p>Find concise answers about ${data.title.toLowerCase()}, suitability, installation and performance.</p></div><div class="prod-faq-list" data-reveal>${renderFaqs(data.faqs)}</div></div></section>`;

    const schema = { "@context": "https://schema.org", "@graph": [
      { "@type": "WebPage", "name": data.title, "url": `/${data.slug}/`, "description": data.intro },
      { "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "/" }, { "@type": "ListItem", "position": 2, "name": "Products", "item": `/${data.slug}/` }, { "@type": "ListItem", "position": 3, "name": data.title, "item": `/${data.slug}/` }] },
      { "@type": "FAQPage", "mainEntity": data.faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }
    ] };
    const schemaScript = document.createElement("script");
    schemaScript.type = "application/ld+json";
    schemaScript.textContent = JSON.stringify(schema);
    document.head.append(schemaScript);
  };

  const key = document.body.dataset.productPage;
  if (key && pages[key]) renderPage(pages[key]);
})();
